//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberDetail2
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public string passw { get; set; }
        public string userrole { get; set; }
    }
}
